import 'dart:typed_data';
import 'package:test/test.dart';
import 'package:pdfbox_dart/src/ucar/jpeg/jj2000/j2k/entropy/decoder/mq_decoder.dart';
import 'package:pdfbox_dart/src/ucar/jpeg/jj2000/j2k/entropy/decoder/byte_input_buffer.dart';

void main() {
  group('MQDecoder', () {
    final initStates = [0, 7, 3, 12];
    final numCtxt = initStates.length;

    final scenarioOneCtx = [
      0, 0, 0, 0,
      1, 1, 1,
      2, 2,
      3, 3, 3, 3,
      1, 2, 0
    ];

    final scenarioOneBits = [
      0, 1, 0, 0,
      1, 0, 1,
      1, 0,
      0, 0, 1, 1,
      1, 0, 1
    ];

    test('decodeSymbolsMatchesReferenceCoder', () {
      // Fixture generated by Java MQCoder: 2A 91 A4
      final encoded = Uint8List.fromList([0x2A, 0x91, 0xA4]);
      
      final decoder = MQDecoder(ByteInputBuffer(encoded), numCtxt, initStates);
      final decoded = List<int>.filled(scenarioOneBits.length, 0);
      
      decoder.decodeSymbols(decoded, scenarioOneCtx, decoded.length);
      
      expect(decoded, equals(scenarioOneBits));
    });

    test('fastDecodeSymbolsHandlesLongMpsRuns', () {
      const runContext = 0;
      const runLength = 12;
      const runBit = 0;

      final contexts = List<int>.filled(runLength, runContext);
      final bits = List<int>.filled(runLength, runBit);

      // Fixture generated by Java MQCoder: 7D
      final encoded = Uint8List.fromList([0x7D]);
      
      final decoder = MQDecoder(ByteInputBuffer(encoded), numCtxt, initStates);
      final buffer = List<int>.filled(runLength, 0);
      
      final usedFast = decoder.fastDecodeSymbols(buffer, runContext, runLength);
      
      if (usedFast) {
        expect(buffer[0], equals(runBit), reason: 'bit MPS inesperado');
      } else {
        for (final value in buffer) {
          expect(value, equals(runBit), reason: 'bit divergente no modo normal');
        }
      }

      decoder.nextSegment(encoded, 0, encoded.length);
      decoder.resetCtxts();
      
      final decoded = List<int>.filled(runLength, 0);
      decoder.decodeSymbols(decoded, contexts, runLength);
      
      expect(decoded, equals(bits));
    });
  });
}
