import 'cff_charset.dart';

class _ExpertCharEntry {
  const _ExpertCharEntry(this.sid, this.name);

  final int sid;
  final String name;
}

/// Expert charset used when the charset id equals 1.
class CFFExpertCharset extends EmbeddedCharset {
  CFFExpertCharset._internal() : super(isCidFont: false) {
    var gid = 0;
    for (final entry in _entries) {
      addSID(gid++, entry.sid, entry.name);
    }
  }

  static CFFExpertCharset get instance => _instance;

  static final CFFExpertCharset _instance = CFFExpertCharset._internal();
}

const List<_ExpertCharEntry> _entries = <_ExpertCharEntry>[
  _ExpertCharEntry(0, '.notdef'),
  _ExpertCharEntry(1, 'space'),
  _ExpertCharEntry(229, 'exclamsmall'),
  _ExpertCharEntry(230, 'Hungarumlautsmall'),
  _ExpertCharEntry(231, 'dollaroldstyle'),
  _ExpertCharEntry(232, 'dollarsuperior'),
  _ExpertCharEntry(233, 'ampersandsmall'),
  _ExpertCharEntry(234, 'Acutesmall'),
  _ExpertCharEntry(235, 'parenleftsuperior'),
  _ExpertCharEntry(236, 'parenrightsuperior'),
  _ExpertCharEntry(237, 'twodotenleader'),
  _ExpertCharEntry(238, 'onedotenleader'),
  _ExpertCharEntry(13, 'comma'),
  _ExpertCharEntry(14, 'hyphen'),
  _ExpertCharEntry(15, 'period'),
  _ExpertCharEntry(99, 'fraction'),
  _ExpertCharEntry(239, 'zerooldstyle'),
  _ExpertCharEntry(240, 'oneoldstyle'),
  _ExpertCharEntry(241, 'twooldstyle'),
  _ExpertCharEntry(242, 'threeoldstyle'),
  _ExpertCharEntry(243, 'fouroldstyle'),
  _ExpertCharEntry(244, 'fiveoldstyle'),
  _ExpertCharEntry(245, 'sixoldstyle'),
  _ExpertCharEntry(246, 'sevenoldstyle'),
  _ExpertCharEntry(247, 'eightoldstyle'),
  _ExpertCharEntry(248, 'nineoldstyle'),
  _ExpertCharEntry(27, 'colon'),
  _ExpertCharEntry(28, 'semicolon'),
  _ExpertCharEntry(249, 'commasuperior'),
  _ExpertCharEntry(250, 'threequartersemdash'),
  _ExpertCharEntry(251, 'periodsuperior'),
  _ExpertCharEntry(252, 'questionsmall'),
  _ExpertCharEntry(253, 'asuperior'),
  _ExpertCharEntry(254, 'bsuperior'),
  _ExpertCharEntry(255, 'centsuperior'),
  _ExpertCharEntry(256, 'dsuperior'),
  _ExpertCharEntry(257, 'esuperior'),
  _ExpertCharEntry(258, 'isuperior'),
  _ExpertCharEntry(259, 'lsuperior'),
  _ExpertCharEntry(260, 'msuperior'),
  _ExpertCharEntry(261, 'nsuperior'),
  _ExpertCharEntry(262, 'osuperior'),
  _ExpertCharEntry(263, 'rsuperior'),
  _ExpertCharEntry(264, 'ssuperior'),
  _ExpertCharEntry(265, 'tsuperior'),
  _ExpertCharEntry(266, 'ff'),
  _ExpertCharEntry(109, 'fi'),
  _ExpertCharEntry(110, 'fl'),
  _ExpertCharEntry(267, 'ffi'),
  _ExpertCharEntry(268, 'ffl'),
  _ExpertCharEntry(269, 'parenleftinferior'),
  _ExpertCharEntry(270, 'parenrightinferior'),
  _ExpertCharEntry(271, 'Circumflexsmall'),
  _ExpertCharEntry(272, 'hyphensuperior'),
  _ExpertCharEntry(273, 'Gravesmall'),
  _ExpertCharEntry(274, 'Asmall'),
  _ExpertCharEntry(275, 'Bsmall'),
  _ExpertCharEntry(276, 'Csmall'),
  _ExpertCharEntry(277, 'Dsmall'),
  _ExpertCharEntry(278, 'Esmall'),
  _ExpertCharEntry(279, 'Fsmall'),
  _ExpertCharEntry(280, 'Gsmall'),
  _ExpertCharEntry(281, 'Hsmall'),
  _ExpertCharEntry(282, 'Ismall'),
  _ExpertCharEntry(283, 'Jsmall'),
  _ExpertCharEntry(284, 'Ksmall'),
  _ExpertCharEntry(285, 'Lsmall'),
  _ExpertCharEntry(286, 'Msmall'),
  _ExpertCharEntry(287, 'Nsmall'),
  _ExpertCharEntry(288, 'Osmall'),
  _ExpertCharEntry(289, 'Psmall'),
  _ExpertCharEntry(290, 'Qsmall'),
  _ExpertCharEntry(291, 'Rsmall'),
  _ExpertCharEntry(292, 'Ssmall'),
  _ExpertCharEntry(293, 'Tsmall'),
  _ExpertCharEntry(294, 'Usmall'),
  _ExpertCharEntry(295, 'Vsmall'),
  _ExpertCharEntry(296, 'Wsmall'),
  _ExpertCharEntry(297, 'Xsmall'),
  _ExpertCharEntry(298, 'Ysmall'),
  _ExpertCharEntry(299, 'Zsmall'),
  _ExpertCharEntry(300, 'colonmonetary'),
  _ExpertCharEntry(301, 'onefitted'),
  _ExpertCharEntry(302, 'rupiah'),
  _ExpertCharEntry(303, 'Tildesmall'),
  _ExpertCharEntry(304, 'exclamdownsmall'),
  _ExpertCharEntry(305, 'centoldstyle'),
  _ExpertCharEntry(306, 'Lslashsmall'),
  _ExpertCharEntry(307, 'Scaronsmall'),
  _ExpertCharEntry(308, 'Zcaronsmall'),
  _ExpertCharEntry(309, 'Dieresissmall'),
  _ExpertCharEntry(310, 'Brevesmall'),
  _ExpertCharEntry(311, 'Caronsmall'),
  _ExpertCharEntry(312, 'Dotaccentsmall'),
  _ExpertCharEntry(313, 'Macronsmall'),
  _ExpertCharEntry(314, 'figuredash'),
  _ExpertCharEntry(315, 'hypheninferior'),
  _ExpertCharEntry(316, 'Ogoneksmall'),
  _ExpertCharEntry(317, 'Ringsmall'),
  _ExpertCharEntry(318, 'Cedillasmall'),
  _ExpertCharEntry(158, 'onequarter'),
  _ExpertCharEntry(155, 'onehalf'),
  _ExpertCharEntry(163, 'threequarters'),
  _ExpertCharEntry(319, 'questiondownsmall'),
  _ExpertCharEntry(320, 'oneeighth'),
  _ExpertCharEntry(321, 'threeeighths'),
  _ExpertCharEntry(322, 'fiveeighths'),
  _ExpertCharEntry(323, 'seveneighths'),
  _ExpertCharEntry(324, 'onethird'),
  _ExpertCharEntry(325, 'twothirds'),
  _ExpertCharEntry(326, 'zerosuperior'),
  _ExpertCharEntry(150, 'onesuperior'),
  _ExpertCharEntry(164, 'twosuperior'),
  _ExpertCharEntry(169, 'threesuperior'),
  _ExpertCharEntry(327, 'foursuperior'),
  _ExpertCharEntry(328, 'fivesuperior'),
  _ExpertCharEntry(329, 'sixsuperior'),
  _ExpertCharEntry(330, 'sevensuperior'),
  _ExpertCharEntry(331, 'eightsuperior'),
  _ExpertCharEntry(332, 'ninesuperior'),
  _ExpertCharEntry(333, 'zeroinferior'),
  _ExpertCharEntry(334, 'oneinferior'),
  _ExpertCharEntry(335, 'twoinferior'),
  _ExpertCharEntry(336, 'threeinferior'),
  _ExpertCharEntry(337, 'fourinferior'),
  _ExpertCharEntry(338, 'fiveinferior'),
  _ExpertCharEntry(339, 'sixinferior'),
  _ExpertCharEntry(340, 'seveninferior'),
  _ExpertCharEntry(341, 'eightinferior'),
  _ExpertCharEntry(342, 'nineinferior'),
  _ExpertCharEntry(343, 'centinferior'),
  _ExpertCharEntry(344, 'dollarinferior'),
  _ExpertCharEntry(345, 'periodinferior'),
  _ExpertCharEntry(346, 'commainferior'),
  _ExpertCharEntry(347, 'Agravesmall'),
  _ExpertCharEntry(348, 'Aacutesmall'),
  _ExpertCharEntry(349, 'Acircumflexsmall'),
  _ExpertCharEntry(350, 'Atildesmall'),
  _ExpertCharEntry(351, 'Adieresissmall'),
  _ExpertCharEntry(352, 'Aringsmall'),
  _ExpertCharEntry(353, 'AEsmall'),
  _ExpertCharEntry(354, 'Ccedillasmall'),
  _ExpertCharEntry(355, 'Egravesmall'),
  _ExpertCharEntry(356, 'Eacutesmall'),
  _ExpertCharEntry(357, 'Ecircumflexsmall'),
  _ExpertCharEntry(358, 'Edieresissmall'),
  _ExpertCharEntry(359, 'Igravesmall'),
  _ExpertCharEntry(360, 'Iacutesmall'),
  _ExpertCharEntry(361, 'Icircumflexsmall'),
  _ExpertCharEntry(362, 'Idieresissmall'),
  _ExpertCharEntry(363, 'Ethsmall'),
  _ExpertCharEntry(364, 'Ntildesmall'),
  _ExpertCharEntry(365, 'Ogravesmall'),
  _ExpertCharEntry(366, 'Oacutesmall'),
  _ExpertCharEntry(367, 'Ocircumflexsmall'),
  _ExpertCharEntry(368, 'Otildesmall'),
  _ExpertCharEntry(369, 'Odieresissmall'),
  _ExpertCharEntry(370, 'OEsmall'),
  _ExpertCharEntry(371, 'Oslashsmall'),
  _ExpertCharEntry(372, 'Ugravesmall'),
  _ExpertCharEntry(373, 'Uacutesmall'),
  _ExpertCharEntry(374, 'Ucircumflexsmall'),
  _ExpertCharEntry(375, 'Udieresissmall'),
  _ExpertCharEntry(376, 'Yacutesmall'),
  _ExpertCharEntry(377, 'Thornsmall'),
  _ExpertCharEntry(378, 'Ydieresissmall'),
];
