import 'dart:convert';
import 'dart:io';

void main() {
  final root = Directory.current.path;
  final glyphListPath =
      '$root/pdfbox-java/pdfbox/src/main/resources/org/apache/pdfbox/resources/glyphlist/glyphlist.txt';
  final zapfPath =
      '$root/pdfbox-java/pdfbox/src/main/resources/org/apache/pdfbox/resources/glyphlist/zapfdingbats.txt';

  final adobe = _parseGlyphList(File(glyphListPath));
  final zapf = _parseGlyphList(File(zapfPath));

  final buffer = StringBuffer()
    ..writeln('// Generated by scripts/generate_glyph_list.dart -- do not edit manually.')
    ..writeln('// ignore_for_file: prefer_const_literals_to_create_immutables, prefer_single_quotes')
    ..writeln('')
    ..writeln('const Map<String, List<int>> kAdobeGlyphListHex = <String, List<int>>{');

  adobe.forEach((name, values) {
    final hexList = values.map((value) => '0x${value.toRadixString(16).toUpperCase()}');
    buffer.writeln("  '$name': <int>[${hexList.join(', ')}],");
  });
  buffer
    ..writeln('};')
    ..writeln('')
    ..writeln('const Map<String, List<int>> kZapfDingbatsGlyphListHex = <String, List<int>>{');
  zapf.forEach((name, values) {
    final hexList = values.map((value) => '0x${value.toRadixString(16).toUpperCase()}');
    buffer.writeln("  '$name': <int>[${hexList.join(', ')}],");
  });
  buffer.writeln('};');

  final outputPath =
      '$root/lib/src/fontbox/resources/glyph_list_data.dart';
  File(outputPath)
    ..createSync(recursive: true)
    ..writeAsStringSync(buffer.toString());
}

Map<String, List<int>> _parseGlyphList(File file) {
  final result = <String, List<int>>{};
  for (final rawLine in file.readAsLinesSync(encoding: latin1)) {
    final line = rawLine.trim();
    if (line.isEmpty || line.startsWith('#')) {
      continue;
    }
    final parts = line.split(';');
    if (parts.length < 2) {
      throw FormatException('Invalid glyph list entry', line);
    }
    final name = parts[0];
    final codes = parts[1].split(RegExp(r'\s+')).where((element) => element.isNotEmpty);
    final codePoints = <int>[];
    for (final code in codes) {
      codePoints.add(int.parse(code, radix: 16));
    }
    result[name] = codePoints;
  }
  return result;
}
