import 'dart:io';

void main() {
  final root = Directory.current.path;
  final symbolPath =
      '$root/pdfbox-java/pdfbox/src/main/resources/org/apache/pdfbox/resources/afm/Symbol.afm';
  final zapfPath =
      '$root/pdfbox-java/pdfbox/src/main/resources/org/apache/pdfbox/resources/afm/ZapfDingbats.afm';

  final symbolMap = _parseAfm(File(symbolPath));
  final zapfMap = _parseAfm(File(zapfPath));

  final buffer = StringBuffer()
    ..writeln('// Generated by scripts/generate_type1_encoding_tables.dart -- do not edit manually.')
    ..writeln('const Map<int, String> kSymbolEncoding = <int, String>{');

  final symbolCodes = symbolMap.keys.toList()..sort();
  for (final code in symbolCodes) {
    buffer.writeln("  $code: '${symbolMap[code]}',");
  }
  buffer
    ..writeln('};')
    ..writeln('')
    ..writeln('const Map<int, String> kZapfDingbatsEncoding = <int, String>{');

  final zapfCodes = zapfMap.keys.toList()..sort();
  for (final code in zapfCodes) {
    buffer.writeln("  $code: '${zapfMap[code]}',");
  }
  buffer.writeln('};');

  final outputPath = '$root/lib/src/fontbox/resources/type1_encoding_data.dart';
  File(outputPath)
    ..createSync(recursive: true)
    ..writeAsStringSync(buffer.toString());
}

Map<int, String> _parseAfm(File file) {
  final map = <int, String>{};
  final pattern = RegExp(r'^C\s+(-?\d+)\s*;.*?N\s+([^\s;]+)');
  for (final line in file.readAsLinesSync()) {
    final match = pattern.firstMatch(line);
    if (match == null) {
      continue;
    }
    final code = int.parse(match.group(1)!);
    if (code < 0) {
      continue;
    }
    final name = match.group(2)!;
    map[code] = name;
  }
  return map;
}
