// ignore_for_file: avoid_print
/// Script para gerar código Dart com fontes embedadas (Base64).
///
/// Uso:
///   dart run scripts/generate_embedded_fonts.dart
///
/// Este script lê os arquivos TTF do diretório resources/fontes/ e gera
/// um arquivo Dart com as fontes codificadas em Base64, permitindo uso
/// offline sem dependência de fontes do sistema.

import 'dart:convert';
import 'dart:io';

/// Mapeamento de arquivos TTF para nomes de fontes padrão PDF (Standard 14).
const Map<String, List<String>> fontFileToNames = {
  'helvetica.ttf': ['Helvetica', 'Arial', 'ArialMT'],
  'helvetica-bold.ttf': ['Helvetica-Bold', 'Arial-Bold', 'Arial-BoldMT'],
  'times.ttf': ['Times-Roman', 'Times', 'TimesNewRoman', 'TimesNewRomanPSMT'],
  'Times New Roman.ttf': ['Times-Roman', 'TimesNewRoman'],
  'arial.ttf': ['Arial', 'ArialMT'],
  'CourierPrime-Regular.ttf': ['Courier', 'CourierNew', 'CourierNewPSMT'],
  'CourierPrime-Bold.ttf': ['Courier-Bold', 'CourierNew-Bold'],
  'CourierPrime-Italic.ttf': ['Courier-Oblique', 'Courier-Italic'],
  'CourierPrime-BoldItalic.ttf': ['Courier-BoldOblique', 'Courier-BoldItalic'],
  'zapfdingbats.ttf': ['ZapfDingbats'],
};

/// Fontes prioritárias para embed (Standard 14 fonts).
const List<String> priorityFonts = [
  'helvetica.ttf',
  'helvetica-bold.ttf',
  'times.ttf',
  'CourierPrime-Regular.ttf',
  'CourierPrime-Bold.ttf',
  'CourierPrime-Italic.ttf',
  'CourierPrime-BoldItalic.ttf',
  'zapfdingbats.ttf',
];

void main(List<String> args) async {
  final fontsDir = Directory('resources/fontes');
  final outputFile = File('lib/src/pdfbox/pdmodel/font/embedded_fonts.dart');

  if (!fontsDir.existsSync()) {
    print('Erro: Diretório resources/fontes/ não encontrado.');
    print('Execute este script a partir da raiz do projeto pdfbox_dart.');
    exit(1);
  }

  print('=== Gerador de Fontes Embedadas ===\n');

  final buffer = StringBuffer();

  // Header do arquivo gerado
  buffer.writeln('// GENERATED FILE - DO NOT EDIT');
  buffer.writeln('// Generated by: dart run scripts/generate_embedded_fonts.dart');
  buffer.writeln('// Date: ${DateTime.now().toIso8601String()}');
  buffer.writeln('//');
  buffer.writeln('// Este arquivo contém fontes TTF embedadas em Base64 para uso');
  buffer.writeln('// offline, quando fontes do sistema não estão disponíveis.');
  buffer.writeln('');
  buffer.writeln("import 'dart:convert';");
  buffer.writeln("import 'dart:typed_data';");
  buffer.writeln('');
  buffer.writeln('/// Classe que fornece acesso às fontes embedadas.');
  buffer.writeln('class EmbeddedFonts {');
  buffer.writeln('  EmbeddedFonts._();');
  buffer.writeln('');

  // Mapa de nomes de fonte para chave do embed
  final fontNameMap = <String, String>{};
  final embeddedKeys = <String>[];

  // Processar fontes prioritárias
  for (final fontFile in priorityFonts) {
    final file = File('${fontsDir.path}/$fontFile');
    if (!file.existsSync()) {
      print('  [SKIP] $fontFile não encontrado');
      continue;
    }

    final bytes = file.readAsBytesSync();
    final base64 = base64Encode(bytes);
    final keyName = _toVariableName(fontFile);

    print('  [OK] $fontFile (${bytes.length} bytes -> ${base64.length} chars base64)');

    embeddedKeys.add(keyName);

    // Adicionar mapeamento de nomes
    final names = fontFileToNames[fontFile] ?? [];
    for (final name in names) {
      fontNameMap[name.toLowerCase()] = keyName;
    }

    // Gerar constante base64
    buffer.writeln('  /// $fontFile (${bytes.length} bytes)');
    buffer.writeln("  static const String _${keyName}Base64 = '''");
    buffer.writeln(base64);
    buffer.writeln("''';");
    buffer.writeln('');
  }

  // Gerar getters estáticos para acesso direto
  for (final key in embeddedKeys) {
    buffer.writeln('  static Uint8List? get $key => _getByKey(\'$key\');');
  }
  buffer.writeln('');

  // Mapa de nomes de fonte (lowercase) para chave interna.
  buffer.writeln('  static const Map<String, String> _fontNameToKey = {');
  for (final entry in fontNameMap.entries) {
    buffer.writeln("    '${entry.key}': '${entry.value}',");
  }
  buffer.writeln('  };');
  buffer.writeln('');

  /// Retorna os bytes da fonte embedada pelo nome.
  /// Retorna null se a fonte não estiver disponível.
  buffer.writeln('  static Uint8List? getFontBytes(String fontName) {');
  buffer.writeln('    final key = _fontNameToKey[fontName.toLowerCase()];');
  buffer.writeln('    if (key == null) return null;');
  buffer.writeln('    return _getByKey(key);');
  buffer.writeln('  }');
  buffer.writeln('');

  buffer.writeln('  /// Verifica se uma fonte está disponível.');
  buffer.writeln('  static bool hasFont(String fontName) {');
  buffer.writeln('    return _fontNameToKey.containsKey(fontName.toLowerCase());');
  buffer.writeln('  }');
  buffer.writeln('');

  buffer.writeln('  /// Lista de nomes de fontes disponíveis.');
  buffer.writeln('  static List<String> get availableFonts => _fontNameToKey.keys.toList();');
  buffer.writeln('');

  // Cache para evitar decodificar múltiplas vezes
  buffer.writeln('  static final Map<String, Uint8List> _cache = {};');
  buffer.writeln('');

  buffer.writeln('  static Uint8List? _getByKey(String key) {');
  buffer.writeln('    if (_cache.containsKey(key)) return _cache[key];');
  buffer.writeln('');
  buffer.writeln('    String? base64Data;');
  buffer.writeln('    switch (key) {');
  
  // O switch case para as constantes, mas vamos usar um método helper para decodificar
  for (final key in embeddedKeys) {
    buffer.writeln("      case '$key':");
    buffer.writeln('        base64Data = _${key}Base64;');
    buffer.writeln('        break;');
  }
  buffer.writeln('      default:');
  buffer.writeln('        return null;');
  buffer.writeln('    }');
  buffer.writeln('');
  buffer.writeln('    // Remove newlines and whitespace from base64 string');
  buffer.writeln(r'    final cleanBase64 = base64Data!.replaceAll(RegExp(r"\s+"), "");');
  buffer.writeln('    final bytes = base64Decode(cleanBase64);');
  buffer.writeln('    _cache[key] = bytes;');
  buffer.writeln('    return bytes;');
  buffer.writeln('  }');
  
  buffer.writeln('}');

  // Criar diretório de saída se não existir
  final outputDir = outputFile.parent;
  if (!outputDir.existsSync()) {
    outputDir.createSync(recursive: true);
  }

  // Escrever arquivo
  outputFile.writeAsStringSync(buffer.toString());

  print('\n=== Resultado ===');
  print('Arquivo gerado: ${outputFile.path}');
  print('Fontes embedadas: ${embeddedKeys.length}');
  print('Mapeamentos de nome: ${fontNameMap.length}');
  print('\nPara usar:');
  print("  import 'package:pdfbox_dart/src/pdfbox/pdmodel/font/embedded_fonts.dart';");
  print("  final bytes = EmbeddedFonts.getFontBytes('Helvetica');");
}

/// Converte nome de arquivo para nome de variável Dart válido.
String _toVariableName(String fileName) {
  // Remove extensão
  var name = fileName.replaceAll('.ttf', '');
  // Substitui caracteres inválidos
  name = name.replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_');
  // Remove underscores duplicados
  name = name.replaceAll(RegExp(r'_+'), '_');
  // Remove underscores no início/fim
  name = name.replaceAll(RegExp(r'^_|_$'), '');
  // Converte para camelCase
  final parts = name.split('_');
  if (parts.isEmpty) return 'font';
  return parts.first.toLowerCase() +
      parts.skip(1).map((p) => p.isEmpty ? '' : p[0].toUpperCase() + p.substring(1).toLowerCase()).join();
}
